from typing import Dict
from typing_extensions import TypedDict, List
from langchain.schema import HumanMessage
from app.agents.core.tool import BaseTool
from app.agents.core.system_state import SystemState



class  ConversationState(SystemState):
    
    database: str = "" # The database name
    user_session: str = "" # The user session ID
    chart_type: str = "" # The type of chart to be generated (e.g., bar, line, pie)
    history: List[HumanMessage] = [] # Main the conversation history
    sql_query: str = "" # The SQL query generated by the system
    question:str = "" # The question asked by the user
    question_embedding: list = []
    table_embedding: dict = {} # Dict[str,Dict[str, Dict[str, str]]]  # database, trable , fields
    relevant_schema: str = "" # The relevant schema for the question
    query_result: List = [] # The result of the SQL query
    examples: List = [] # List of examples for few-shot learning
    answer:str = "" # The final answer generated by the system
    result:str =  "" # The result of the SQL query execution
    command:str = "" # The command to be executed (e.g., CONTINUE, NO-SCHEMA, CLARIFY, etc.)

    @classmethod
    def initialize(cls) -> 'ConversationState':
        """
        Initialize the conversation state.
        """
        return {
            "history": [],
            "query_result": [],
            "sql_query": "",
            "chart_type": "",
            "database": "",
            "user_session": "",
            "table_embedding": {},
            "relevant_schema": "",
            "question": "",
            "question_embedding": [],
            "examples": [],
            "answer": "",
            "result": "",
            "command": "",
            "proceed": True,
            "executing_tool":"",
            "task": "",
            "execution_time": 0.0, 
            "execution_history" : [],
            "errors": {},
            "executed_at": "",

        }
        


def initialize_conversation_state_1() -> ConversationState:
    return {
        "history": [], 
        "query_result": [], 
        "sql_query": "", #
        "chart_type": "",
        "database": "",
        "user_session": "",
        "table_embedding": {},
        "relevant_schema": "",
        "question": "",
        "question_embedding": [],
        "examples":[],
        "answer": "",
        "result": "",
        "command":""

    }