name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  # ──────────────────────────────
  # 1. Python tests (matrix 3 APIs)
  # ──────────────────────────────
  test-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api: [core_api, admin_api, metrics_api]
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps + editable install
        run: |
          pip install -r requirements.txt
          pip install -e .

      - name: Run pytest
        run: |
          pytest tests/${{ matrix.api }}

  # ──────────────────────────────
  # 2. Front-end unit/e2e tests
  # ──────────────────────────────
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: |
          npm ci
          npm run test              # jest / vitest / playwright

  # ──────────────────────────────
  # 3. Build & push API containers (matrix)
  # ──────────────────────────────
  build-api:
    needs: [test-backend, test-frontend]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [core_api, admin_api, metrics_api]
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build & push image
        run: |
          az acr build \
            --registry ${{ secrets.ACR_NAME }} \
            --image ${{ matrix.image }}:${{ github.sha }} \
            --file infrastructure/docker/${{ matrix.image }}.Dockerfile .

  # ──────────────────────────────
  # 4. Build & push SPA container
  # ──────────────────────────────
  build-web:
    needs: build-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build & push web image
        run: |
          az acr build \
            --registry ${{ secrets.ACR_NAME }} \
            --image web:${{ github.sha }} \
            --file infrastructure/docker/web.Dockerfile .
