# app/repos/usage_repository.py
from typing import Optional, List, Tuple, Dict, Any
from datetime import date

class IUsageRepository:
    def ensure(self) -> None: ...
    def get_day(self, user_id: str, yyyymmdd: str) -> Optional[Dict[str, Any]]: ...
    def upsert_day(self, user_id: str, yyyymmdd: str, delta_prompt: int, delta_completion: int,
                   model: Optional[str], default_quota: int) -> Dict[str, Any]: ...
    def set_quota(self, user_id: str, quota: int) -> None: ...
    def get_range(self, user_id: str, start: date, end: date) -> List[Dict[str, Any]]: ...
