import os


OPEN_AI_KEY = os.getenv("AZURE_OPENAI_KEY")
OPENAI_DEPLOYMENT = os.getenv("AZURE_OPENAI_DEPLOYMENT")
OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
TENANT_ID = os.getenv("AZURE_AD_TENANT_ID")
CLIENT_ID = os.getenv("AZURE_AD_CLIENT_ID")  # App ID of the backend API
USE_KEY_VAULT_TO_GET_CONNECTION_STRING = os.getenv("USE_KEY_VAULT_TO_GET_CONNECTION_STRING", "false").lower() == "true"
KEY_VAULT_URI = os.getenv("KEY_VAULT_URI")
SQL_CONNECTION_STRING_SECRET_NAME = os.getenv("SQL_CONNECTION_STRING_SECRET_NAME")  
SQL_CONNECTION_STRING = os.getenv("SQL_CONNECTION_STRING")
CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", "http://localhost:3000,http://localhost:5173,http://example.com")
APPLICATIONINSIGHTS_CONNECTION_STRING = os.getenv("APPLICATIONINSIGHTS_CONNECTION_STRING")
INDEX_NAME = os.environ.get("AZURE_SEARCH_INDEX_NAME", "nl2sql-index")
SEARCH_SERVICE = os.environ.get("AZURE_SEARCH_SERVICE_NAME")
SEARCH_API_KEY = os.environ.get("AZURE_SEARCH_API_KEY")

