name: Deploy Azure Functions
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Azure Function
      uses: Azure/functions-action@v1
      with:
        app-name: "text-sql-azure-function"
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        package: "."